version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_prod
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwerty.123
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=django_prod
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwerty.123
    depends_on:
      - db
  grafana:
    image: grafana/grafana:9.2.15
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
