# Generated by Django 4.1.7 on 2023-05-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housing',
            options={'verbose_name': 'Housing', 'verbose_name_plural': 'Housings'},
        ),
        migrations.AlterModelOptions(
            name='housingtype',
            options={'verbose_name': 'HousingType', 'verbose_name_plural': 'HousingTypes'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='numberofrooms',
            options={'verbose_name': 'NumberOfRoom', 'verbose_name_plural': 'NumberOfRooms'},
        ),
    ]
